In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd
import os

In [2]:
os.chdir(os.getcwd())

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
print('No. of missing rows of Male :',df.loc[df.Sex=='male','Age'].isnull().sum())
print('No. of missing rows of Female :',df.loc[df.Sex=='female','Age'].isnull().sum())

No. of missing rows of Male : 124
No. of missing rows of Female : 53


In [7]:
df.Age[(df.Age.isnull()) & (df.Sex=='male')]= round(df.loc[df.Sex=='male','Age'].mean())
df.Age[(df.Age.isnull()) & (df.Sex=='female')]= round(df.loc[df.Sex=='female','Age'].mean())

C:\Users\Shubham\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Shubham\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [8]:
print('No. of missing rows of Male :',df.loc[df.Sex=='male','Age'].isnull().sum())
print('No. of missing rows of Female :',df.loc[df.Sex=='female','Age'].isnull().sum())

No. of missing rows of Male : 0
No. of missing rows of Female : 0


In [9]:
df.Embarked[df.Embarked.isnull()]='S'

C:\Users\Shubham\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [10]:
pd.crosstab(index = df.SibSp,columns = df.Survived) #Pclass,Sex,Age,SibSp,parch,Fare,Embarked

Survived    0    1
SibSp             
0         398  210
1          97  112
2          15   13
3          12    4
4          15    3
5           5    0
8           7    0

In [32]:
x = df.iloc[:,[2,4,5,6,7,9,11]].values
y = df.iloc[:,1].values
x

array([[3, 'male', 22.0, ..., 0, 7.25, 'S'],
       [1, 'female', 38.0, ..., 0, 71.2833, 'C'],
       [3, 'female', 26.0, ..., 0, 7.925, 'S'],
       ...,
       [3, 'female', 28.0, ..., 2, 23.45, 'S'],
       [1, 'male', 26.0, ..., 0, 30.0, 'C'],
       [3, 'male', 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [13]:
labelencoder = LabelEncoder()
x[:,1] = labelencoder.fit_transform(x[:,1])
display(pd.DataFrame(x))
#onehotencoder = OneHotEncoder(categorical_features=[1])
#x = onehotencoder.fit_transform(x).toarray()

0  1   2  3  4        5  6
0    3  1  22  1  0     7.25  S
1    1  0  38  1  0  71.2833  C
2    3  0  26  0  0    7.925  S
3    1  0  35  1  0     53.1  S
4    3  1  35  0  0     8.05  S
5    3  1  31  0  0   8.4583  Q
6    1  1  54  0  0  51.8625  S
7    3  1   2  3  1   21.075  S
8    3  0  27  0  2  11.1333  S
9    2  0  14  1  0  30.0708  C
10   3  0   4  1  1     16.7  S
11   1  0  58  0  0    26.55  S
12   3  1  20  0  0     8.05  S
13   3  1  39  1  5   31.275  S
14   3  0  14  0  0   7.8542  S
15   2  0  55  0  0       16  S
16   3  1   2  4  1   29.125  Q
17   2  1  31  0  0       13  S
18   3  0  31  1  0       18  S
19   3  0  28  0  0    7.225  C
20   2  1  35  0  0       26  S
21   2  1  34  0  0       13  S
22   3  0  15  0  0   8.0292  Q
23   1  1  28  0  0     35.5  S
24   3  0   8  3  1   21.075  S
25   3  0  38  1  5  31.3875  S
26   3  1  31  0  0    7.225  C
27   1  1  19  3  2      263  S
28   3  0  28  0  0   7.8792  Q
29   3  1  31  0  0   7.8958  S
..  .. ..  .. .. ..      ... ..
861  2  1  21  1  0     11.5  S
862  1  0  48  0  0  25.9292  S
863  3  0  28  8  2    69.55  S
864  2  1  24  0  0       13  S
865  2  0  42  0  0       13  S
866  2  0  27  1  0  13.8583  C
867  1  1  31  0  0  50.4958  S
868  3  1  31  0  0      9.5  S
869  3  1   4  1  1  11.1333  S
870  3  1  26  0  0   7.8958  S
871  1  0  47  1  1  52.5542  S
872  1  1  33  0  0        5  S
873  3  1  47  0  0        9  S
874  2  0  28  1  0       24  C
875  3  0  15  0  0    7.225  C
876  3  1  20  0  0   9.8458  S
877  3  1  19  0  0   7.8958  S
878  3  1  31  0  0   7.8958  S
879  1  0  56  0  1  83.1583  C
880  2  0  25  0  1       26  S
881  3  1  33  0  0   7.8958  S
882  3  0  22  0  0  10.5167  S
883  2  1  28  0  0     10.5  S
884  3  1  25  0  0     7.05  S
885  3  0  39  0  5   29.125  Q
886  2  1  27  0  0       13  S
887  1  0  19  0  0       30  S
888  3  0  28  1  2    23.45  S
889  1  1  26  0  0       30  C
890  3  1  32  0  0     7.75  Q

[891 rows x 7 columns]

In [14]:
labelencoder = LabelEncoder()
x[:,6] = labelencoder.fit_transform(x[:,6])

onehotencoder = OneHotEncoder(categorical_features=[6])
x = onehotencoder.fit_transform(x).toarray()

In [15]:
from sklearn.cross_validation import train_test_split

C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
model = LogisticRegression(random_state=0)
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
y_pred = model.predict(x_test)

In [20]:
y_pred

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[143,  25],
       [ 28,  72]], dtype=int64)

In [23]:
test = pd.read_csv('test.csv')

In [24]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [25]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [26]:
test.Age[(test.Age.isnull()) & (test.Sex=='male')]= round(test.loc[test.Sex=='male','Age'].mean())
test.Age[(test.Age.isnull()) & (test.Sex=='female')]= round(test.loc[test.Sex=='female','Age'].mean())

C:\Users\Shubham\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Shubham\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [27]:
test.Fare[(test.Fare.isnull()) & (test.Embarked=='S')]= round(test.loc[test.Embarked=='S','Fare'].mean())

C:\Users\Shubham\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [28]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [29]:
test1=test[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
test1.head()
x = test1.iloc[:,:].values

In [30]:
labelencoder = LabelEncoder()
x[:,1] = labelencoder.fit_transform(x[:,1])

In [31]:
labelencoder = LabelEncoder()
x[:,6] = labelencoder.fit_transform(x[:,6])

onehotencoder = OneHotEncoder(categorical_features=[6])
x = onehotencoder.fit_transform(x).toarray()

In [32]:
y_pred = model.predict(x)
test['Survived'] = pd.DataFrame(y_pred)

In [33]:
test = pd.concat([test['PassengerId'],test['Survived']], axis=1)

In [34]:
test.loc[test.Survived == 1].count()

PassengerId    157
Survived       157
dtype: int64

In [35]:
writer = pd.ExcelWriter('predict.xlsx')
test.to_excel(writer)
writer.save()